return {
	Number = require(script["Number"]),
	Model = require(script["Model"]),
	Color = require(script["Color"]),
	Challenges = require(script["Challenges"]),
	String = require(script["String"]),
	Table = require(script["Table"]),
	-- GenerateId = function(length: number?)
	-- 	length = length or 16
	-- 	local chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	-- 	local id = ""
	-- 	for i = 1, length do
	-- 		local rand = math.random(1, #chars)
	-- 		id ..= string.sub(chars, rand, rand)
	-- 	end
	-- 	return id
	-- end,
}
